### PR TITLE
Info files

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Review by LraiZer — CHANGES_REQUESTED** [review]
some of the file names require attention, can only accept filenames that contain text, numbers, hypen, underscore with no spaces

also 2 makefiles and a configure file require attention for the files to be built into image.

info SUBDIRS missing in: commando/cdk/root_dream/var_init/etc/Makefile.am

missing file Makefile.am: commando/cdk/root_dream/var_init/etc/info/Makefile.am

missing call in cdk/configure.ac for root_dream/var_init/etc/info/Makefile

**Comment by AbuBaniaz** [comment]
Need help with this
"missing call in cdk/configure.ac for root_dream/var_init/etc/info/Makefile"

**Comment by LraiZer** [comment]
at bottom of cdk/configure.ac inbetween headers and init.d for the boxtype dreambox you need to insert a line to build the info files into the dreambox image: root_dream/var_init/etc/info/Makefile

```
dreambox)

AC_CONFIG_FILES([
```

root_dream/var_init/etc/headers/Makefile

root_dream/var_init/etc/info/Makefile

root_dream/var_init/etc/init.d/Makefile`

**Review by LraiZer — APPROVED** [review]
Thanks

**Pull request merged**
