### PR TITLE
[scan.conf] move decimal points

### PR DESCRIPTION
**Pull request by AbuBaniaz**
Adjust decimal points placement for people using a motor

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Added with this commit.
https://github.com/UkCvs/commando/commit/f463dc8b23c4a4a1b0f37a3e50cf069cb5c567c1

Really isn't hard to merge Al. Honest. Try it next time.

There is a new option to squash and merge.

**Comment by PaphosAL** [comment]
Abu- there were other (NetID) edits in there too, not just your request, m8!

Cannot find the latest VM channel listings PDF by category / Ch number. 
HELP!

Thanks AL ;)

**Comment by LraiZer** [comment]
@AbuBaniaz 
There is no motor menu available when the box is detected as DVB-C. PaphosAL overwrites the DVB-S scan.conf with this DVB-C scan.conf-c at first boot if I'm not mistaken when it is detected as DVB-C? Unless you make a backup image on a DVB-C box and then flash it to a DVB-S box, it seems a little pointless to adjust decimal points placement in this file anyway.

@PaphosAL 
[Maybe here](https://my.virginmedia.com/content/dam/virgoBrowse/docs/VirginMediaTVChannelGuide.pdf)

**Comment by AbuBaniaz** [comment]
Perhaps we can make amendments to the correct file for satellite?

**Comment by PaphosAL** [comment]
default scan.conf files for dvb-c and dvb-s frontends were both removed over a week ago, guys. LraiZer does these in his cpp coding, which overwrote our defaults in any case...

NOT a good idea to use a backup from DM500C to flash to DM500S, as ALL the sat-related files will already have been REMOVED on first boot! Same applies vice-versa!

If you run both N1 platforms in your gaff, ALWAYS use the latest C16 build to flash the 'other' box with!
Cheers- AL

**Pull request closed without merging**
